name: Autotests

# Controls when the action will run. 
# Triggers the workflow on push request
# events but only for the development branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  # Execute tests on windows server. Test scenario:
  # - Import reg files with "issues"
  # - Execute script with few parameter combinations
  # - Check results 
  Test-Before-Release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE (job can access it)
    - uses: actions/checkout@v2

    # Execution shell: pwsh (PowerShell 7.x)
    - name: Execute tests
      run: |
        Set-ExecutionPolicy ByPass
        . $ENV:GITHUB_WORKSPACE\Test\Start-Tests.ps1
